/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AttackPathsRouteImport } from './routes/attack-paths'
import { Route as AttackSurfaceRouteImport } from './routes/attack-surface'
import { Route as FindingsRouteImport } from './routes/findings'
import { Route as RemediationRouteImport } from './routes/remediation'
import { Route as ScopeRouteImport } from './routes/scope'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackPathsRoute = AttackPathsRouteImport.update({
  id: '/attack-paths',
  path: '/attack-paths',
  getParentRoute: () => rootRouteImport,
} as any)
const AttackSurfaceRoute = AttackSurfaceRouteImport.update({
  id: '/attack-surface',
  path: '/attack-surface',
  getParentRoute: () => rootRouteImport,
} as any)
const FindingsRoute = FindingsRouteImport.update({
  id: '/findings',
  path: '/findings',
  getParentRoute: () => rootRouteImport,
} as any)
const RemediationRoute = RemediationRouteImport.update({
  id: '/remediation',
  path: '/remediation',
  getParentRoute: () => rootRouteImport,
} as any)
const ScopeRoute = ScopeRouteImport.update({
  id: '/scope',
  path: '/scope',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/attack-paths': typeof AttackPathsRoute
  '/attack-surface': typeof AttackSurfaceRoute
  '/findings': typeof FindingsRoute
  '/remediation': typeof RemediationRoute
  '/scope': typeof ScopeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attack-paths': typeof AttackPathsRoute
  '/attack-surface': typeof AttackSurfaceRoute
  '/findings': typeof FindingsRoute
  '/remediation': typeof RemediationRoute
  '/scope': typeof ScopeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/attack-paths': typeof AttackPathsRoute
  '/attack-surface': typeof AttackSurfaceRoute
  '/findings': typeof FindingsRoute
  '/remediation': typeof RemediationRoute
  '/scope': typeof ScopeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/attack-paths'
    | '/attack-surface'
    | '/findings'
    | '/remediation'
    | '/scope'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attack-paths'
    | '/attack-surface'
    | '/findings'
    | '/remediation'
    | '/scope'
  id:
    | '__root__'
    | '/'
    | '/attack-paths'
    | '/attack-surface'
    | '/findings'
    | '/remediation'
    | '/scope'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AttackPathsRoute: typeof AttackPathsRoute
  AttackSurfaceRoute: typeof AttackSurfaceRoute
  FindingsRoute: typeof FindingsRoute
  RemediationRoute: typeof RemediationRoute
  ScopeRoute: typeof ScopeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack-paths': {
      id: '/attack-paths'
      path: '/attack-paths'
      fullPath: '/attack-paths'
      preLoaderRoute: typeof AttackPathsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attack-surface': {
      id: '/attack-surface'
      path: '/attack-surface'
      fullPath: '/attack-surface'
      preLoaderRoute: typeof AttackSurfaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/findings': {
      id: '/findings'
      path: '/findings'
      fullPath: '/findings'
      preLoaderRoute: typeof FindingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/remediation': {
      id: '/remediation'
      path: '/remediation'
      fullPath: '/remediation'
      preLoaderRoute: typeof RemediationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scope': {
      id: '/scope'
      path: '/scope'
      fullPath: '/scope'
      preLoaderRoute: typeof ScopeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AttackPathsRoute: AttackPathsRoute,
  AttackSurfaceRoute: AttackSurfaceRoute,
  FindingsRoute: FindingsRoute,
  RemediationRoute: RemediationRoute,
  ScopeRoute: ScopeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
